#????????????????????(???tomcat)??????8080??????????????8081
server:
  port: 9999

upload:
  path: E:/imageUpload/

#???????????
spring:
  servlet:
    multipart:
      max-file-size: 10MB

  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/resources/static/,classpath:/static/,file:${upload.path}
