server:
  port: 9999

# 图片存储位置
upload:
  path: E:/imageUpload/
#  path: /home/FaceDetectionOnHat/imageUpload/

#限制上传图片大小
spring:
  servlet:
    multipart:
      max-file-size: 10MB

  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/resources/static/,classpath:/static/,file:${upload.path}
